# This is a basic workflow to help you get started with Actions

name: CICD-web

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Web
        run: |
          npm install
          npm run build
        
#       # Runs a single command using the runners shell
#       - name: Packing platform
#         run: |
#           npm version
        
      - name: Transit File
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "dist"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /root/ordersystem-vue/

      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /root/ordersystem-vue
            docker build -t web-vue:latest .
            kubectl delete pod $(kubectl get pod -n project1 | grep web-app | awk '{print $1}') -n project1
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          privateKey: ${{ secrets.PRIVATE_KEY}}
